name: steps_tracker_flutter
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  cloud_firestore: ^3.5.0
  cupertino_icons: ^1.0.2
  enum_to_string: ^2.0.1
  firebase_auth: ^3.11.0
  firebase_core: ^1.24.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^11.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  fluttertoast: ^8.0.9
  freezed_annotation: ^2.1.0
  json_theme: ^4.0.1+3
  pedometer: ^3.0.0
  percent_indicator: ^4.2.2
  permission_handler: ^10.0.2
  shared_preferences: ^2.0.15
  syncfusion_flutter_gauges: ^20.3.47

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  json_serializable: ^6.4.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/themes/
